"""Les 22 arcanes majeurs du Tarot de Marseille et leurs sens par thème."""
from __future__ import annotations

from dataclasses import dataclass, field

THEMES: dict[str, str] = {
    "amour": "Amour",
    "travail": "Travail",
    "argent": "Argent",
    "famille": "Famille",
    "perso": "Vie personnelle",
    "futur": "Futur",
}


@dataclass(frozen=True)
class Card:
    number: int
    name: str
    keywords: str
    shadow: str  # sens de la carte à l'envers
    energy: int  # +1 porteuse, 0 neutre, -1 exigeante (à l'endroit)
    themes: dict[str, str] = field(default_factory=dict)


def _c(number, name, keywords, shadow, energy, amour, travail, argent, famille, perso, futur):
    return Card(number, name, keywords, shadow, energy, {
        "amour": amour, "travail": travail, "argent": argent,
        "famille": famille, "perso": perso, "futur": futur,
    })


DECK: tuple[Card, ...] = (
    _c(0, "Le Mat", "liberté, élan, inconnu",
       "imprudence, dispersion, fuite en avant", 0,
       "Une relation qui échappe aux cadres : légèreté, spontanéité, ou peur de s'engager.",
       "Envie de changer d'air, de tout recommencer ; attention à ne pas quitter sans plan.",
       "Dépenses impulsives ou prise de risque : gardez un pied à terre.",
       "Un membre de la famille vit à sa façon ; laissez de l'espace sans rompre le lien.",
       "Vous avez besoin de respirer et d'explorer sans vous justifier.",
       "Une période de départs et d'inattendus s'ouvre, sans itinéraire tracé."),
    _c(1, "Le Bateleur", "initiative, habileté, début",
       "manipulation, hésitation, talents inexploités", 1,
       "Une rencontre ou un nouveau départ : c'est à vous de faire le premier pas.",
       "Tous les outils sont sur la table : lancez le projet, proposez, démontrez.",
       "Vos compétences peuvent générer de nouveaux revenus si vous osez les vendre.",
       "Prenez l'initiative d'un dialogue ou d'un projet commun.",
       "Vous avez plus de ressources que vous ne le croyez ; passez à l'action.",
       "De nouvelles possibilités apparaissent : elles dépendent de votre audace."),
    _c(2, "La Papesse", "intuition, secret, patience",
       "non-dits, fermeture, intuition ignorée", 0,
       "Ce qui se joue est encore silencieux : observez avant de parler, écoutez votre ressenti.",
       "Une information manque ou reste cachée ; étudiez le dossier avant de décider.",
       "Ne signez rien à la hâte ; la prudence et la discrétion protègent vos finances.",
       "Un secret ou un sujet tabou circule dans le foyer ; la douceur le fera émerger.",
       "Un temps d'intériorité : la réponse est déjà en vous, elle demande du calme.",
       "Les choses mûrissent en coulisses ; la patience vous servira mieux que la précipitation."),
    _c(3, "L'Impératrice", "fécondité, douceur, création",
       "excès, étouffement, projets qui stagnent", 1,
       "Tendresse, sensualité et épanouissement : le sentiment se développe naturellement.",
       "Un projet créatif ou un travail d'équipe porte ses fruits ; la croissance est là.",
       "Abondance et récolte : vos efforts passés commencent à rapporter.",
       "Chaleur du foyer, maternité ou soin des proches ; une belle énergie nourricière.",
       "Vous êtes fertile en idées ; prenez soin de vous et de ce qui vous inspire.",
       "Une période de croissance et de réalisations concrètes se prépare."),
    _c(4, "L'Empereur", "structure, autorité, stabilité",
       "rigidité, contrôle, autoritarisme", 1,
       "Un lien stable et protecteur ; attention à ne pas vouloir tout contrôler.",
       "Cadre solide, responsabilités, reconnaissance hiérarchique : c'est le moment de structurer.",
       "Gestion rigoureuse et budget maîtrisé ; bâtissez sur du durable.",
       "Un pilier familial, l'autorité du père ou de celui qui organise : besoin de cadre clair.",
       "Prenez les commandes de votre vie ; posez des règles et tenez-les.",
       "Des fondations solides se construisent ; l'avenir se bâtit par la discipline."),
    _c(5, "Le Pape", "transmission, valeurs, conseil",
       "dogmatisme, conformisme, mauvais conseils", 1,
       "Une relation qui cherche la reconnaissance, voire le mariage ; valeurs partagées.",
       "Un mentor, une formation ou une règle à respecter ; la transmission est clé.",
       "Recourez à un conseiller de confiance (comptable, banquier) avant d'agir.",
       "Traditions, cérémonies, transmission entre générations.",
       "Un enseignement ou un guide vous aide ; restez fidèle à vos valeurs.",
       "Le chemin passe par l'apprentissage et l'appui de personnes de sagesse."),
    _c(6, "L'Amoureux", "choix, attirance, engagement",
       "indécision, tiraillement, mauvais choix", 0,
       "Un choix du cœur est devant vous : attirance forte, mais il faut trancher avec sincérité.",
       "Une décision professionnelle à prendre, ou une association à choisir avec discernement.",
       "Deux options financières s'offrent à vous ; choisissez selon vos valeurs, pas l'envie du moment.",
       "Un choix engage la famille ; la sincérité apaise les tensions.",
       "Vous êtes à un carrefour ; assumer ses désirs vous rendra libre.",
       "Un carrefour majeur approche : votre décision orientera la suite."),
    _c(7, "Le Chariot", "victoire, maîtrise, mouvement",
       "dispersion, conflit, perte de direction", 1,
       "Élan conquérant : vous avancez ; veillez à ce que l'autre suive le mouvement.",
       "Succès, déplacement, promotion : avancez avec détermination.",
       "Les affaires progressent, mais gardez les rênes de vos dépenses.",
       "Déménagement, voyage ou projet familial qui avance ; coordonnez chacun.",
       "Vous reprenez le contrôle ; la volonté est votre moteur.",
       "Une victoire et un mouvement se profilent : soyez déterminé(e) et concentré(e)."),
    _c(8, "La Justice", "équilibre, vérité, décision",
       "injustice, déséquilibre, mauvaise foi", 0,
       "Réciprocité et vérité : la relation demande équité et paroles claires.",
       "Contrats, évaluations, aspects légaux : soyez rigoureux, la clarté l'emporte.",
       "Comptes à équilibrer, règlements à honorer ; vérifiez chaque chiffre.",
       "Partage équitable (héritage, tâches) ; dites les choses franchement.",
       "Faites le point avec honnêteté : chaque action a une conséquence.",
       "Vos choix passés se rééquilibrent ; l'avenir est juste envers la constance."),
    _c(9, "L'Ermite", "recul, sagesse, quête",
       "isolement, repli, retard", 0,
       "Besoin de recul ; solitude choisie ou lien qui demande du temps pour mûrir.",
       "Avancez seul(e) et avec méthode ; un temps de réflexion précède le prochain pas.",
       "Prudence, économies : évitez toute dépense superflue et prenez du recul.",
       "Un proche a besoin de silence ; respectez son rythme.",
       "Temps de bilan et de quête de sens ; retirez-vous pour mieux voir.",
       "Un chemin plus lent mais plus sûr ; la lanterne éclaire pas à pas."),
    _c(10, "La Roue de Fortune", "cycle, chance, tournant",
       "malchance passagère, résistance au changement", 1,
       "Le destin s'en mêle : une rencontre ou un retournement de situation.",
       "Changement de poste ou de contexte ; saisissez l'occasion quand elle passe.",
       "Le vent tourne : gains possibles, mais cycle instable ; ne pariez pas tout.",
       "Des évolutions dans la famille ; ce qui bloquait peut enfin bouger.",
       "Un cycle s'achève et un autre commence ; adaptez-vous.",
       "Un tournant favorable et rapide est annoncé ; restez prêt(e)."),
    _c(11, "La Force", "courage, douceur, maîtrise de soi",
       "doute, colère refoulée, manque de confiance", 1,
       "Une passion apprivoisée par la douceur ; la patience renforce le lien.",
       "Vous avez l'endurance pour surmonter une situation difficile ; restez calme et ferme.",
       "Résistance face aux pressions financières ; votre persévérance paie.",
       "Gérez les conflits avec tendresse plutôt qu'avec la force.",
       "Vous maîtrisez vos peurs ; la vraie force est la constance.",
       "Vous traversez l'épreuve avec succès grâce à votre courage."),
    _c(12, "Le Pendu", "pause, sacrifice, changement de regard",
       "stagnation, sacrifice inutile, refus de lâcher", -1,
       "La relation est suspendue ; un lâcher-prise ou un autre point de vue est nécessaire.",
       "Blocage ou attente ; ne forcez pas, changez d'approche.",
       "Les fonds sont immobilisés ou en attente ; ne décidez rien maintenant.",
       "Un sacrifice est demandé ; regardez la situation autrement.",
       "Faire une pause vous fait avancer ; abandonnez ce que vous ne contrôlez pas.",
       "Un temps d'attente précède le changement ; l'issue viendra avec le lâcher-prise."),
    _c(13, "L'Arcane sans nom", "fin, transformation, renouveau",
       "résistance au changement, deuil qui traîne", -1,
       "Une page se tourne : on coupe ce qui est dépassé pour renaître autrement.",
       "Fin d'un cycle professionnel ; libérez-vous de ce qui ne fonctionne plus.",
       "Coupez dans les dépenses inutiles ; assainissement radical mais salutaire.",
       "Une étape familiale se termine ; l'ancien laisse place au nouveau.",
       "Une mue profonde ; c'est douloureux mais libérateur.",
       "Un grand changement radical ; il libère de l'espace pour la suite."),
    _c(14, "Tempérance", "harmonie, guérison, communication",
       "déséquilibre, excès, impatience", 1,
       "Réconciliation et douceur ; la relation retrouve son équilibre.",
       "Collaboration harmonieuse ; dosez vos efforts et cherchez le compromis.",
       "Gestion équilibrée : petites économies régulières et sécurité.",
       "Paix retrouvée, dialogue apaisé, cohésion familiale.",
       "Retour à l'harmonie ; la guérison est en marche.",
       "Une avancée progressive et paisible ; l'avenir se construit sans heurts."),
    _c(15, "Le Diable", "attachement, tentation, emprise",
       "libération, prise de conscience des chaînes", -1,
       "Passion intense ou dépendance ; attention à la jalousie et à la possessivité.",
       "Pression, dépendance à un poste ou relation toxique ; méfiez-vous de la tentation.",
       "Attachement à l'argent ou dettes qui pèsent ; méfiez-vous des promesses faciles.",
       "Rapports d'emprise ou rancœurs ; nommez ce qui vous lie pour vous en libérer.",
       "Vous êtes lié(e) à une habitude ou une peur ; en prendre conscience libère.",
       "Un risque de se laisser enfermer dans un schéma ; gardez votre liberté de choix."),
    _c(16, "La Maison Dieu", "rupture, choc, libération",
       "choc évité de peu, ébranlement lent", -1,
       "Rupture ou vérité qui éclate ; ce qui est faux s'effondre, ce qui est vrai résiste.",
       "Bouleversement soudain (licenciement, réorganisation) ; reconstruisez sur du solide.",
       "Imprévu financier ; constituez un filet de sécurité.",
       "Tension ou révélation familiale ; l'orage passé, l'air est plus pur.",
       "Vos certitudes s'effondrent pour laisser place à plus de vérité.",
       "Un événement inattendu bouscule la trajectoire ; il ouvre une nouvelle voie."),
    _c(17, "L'Étoile", "espoir, sérénité, inspiration",
       "découragement, manque de foi, rêves différés", 1,
       "Confiance, tendresse et sérénité ; une belle promesse d'amour.",
       "Une bonne étoile : reconnaissance et projets inspirés ; ayez foi.",
       "Une amélioration progressive et durable ; l'espoir est justifié.",
       "Sérénité et réconfort dans le foyer ; guérison des vieilles blessures.",
       "Renouveau de l'espoir ; vous êtes protégé(e) et guidé(e).",
       "Des perspectives lumineuses ; gardez confiance."),
    _c(18, "La Lune", "illusion, sensibilité, incertitude",
       "confusion qui se dissipe, peurs surmontées", -1,
       "Doutes, ambiguïté, sentiments changeants ; ne prenez pas les apparences pour la vérité.",
       "Incertitude ; rumeurs ou informations floues : vérifiez avant d'agir.",
       "Manque de visibilité sur vos finances ; évitez les décisions floues.",
       "Sensibilité à vif, malentendus ; clarifiez ce qui reste dans l'ombre.",
       "Peurs et rêves se mêlent ; écoutez votre intuition sans vous laisser troubler.",
       "L'avenir reste brumeux ; avancez prudemment, la clarté viendra."),
    _c(19, "Le Soleil", "joie, réussite, clarté",
       "bonheur voilé, orgueil, succès retardé", 1,
       "Joie, transparence, amour épanoui ; une relation lumineuse et sincère.",
       "Succès, reconnaissance et clarté : vos efforts sont visibles.",
       "Prospérité et bons résultats ; profitez sans gaspiller.",
       "Bonheur partagé, enfants, chaleur du foyer.",
       "Vitalité, confiance, joie de vivre : vous rayonnez.",
       "Un avenir éclatant ; les obstacles s'éclaircissent."),
    _c(20, "Le Jugement", "éveil, appel, renaissance",
       "regrets, sourde oreille, décision repoussée", 1,
       "Un appel ; on renaît après une crise ou on reprend un lien ancien.",
       "Un tournant décisif ; répondez à l'appel de votre vocation.",
       "Bilan financier et redémarrage ; rétablissez la situation.",
       "Pardon, retrouvailles ou décision collective qui libère.",
       "Un éveil intérieur ; vous vous relevez et répondez à votre vocation.",
       "Un renouveau annoncé : l'heure d'agir selon votre vérité est venue."),
    _c(21, "Le Monde", "accomplissement, plénitude, aboutissement",
       "inachevé, blocage final, dernière étape", 1,
       "Un amour accompli et stable ; harmonie et projet de vie partagé.",
       "Réussite complète, ouverture internationale ; un cycle se boucle avec succès.",
       "Stabilité et réalisation ; vos efforts se concrétisent pleinement.",
       "Union, fête, la famille est réunie et en harmonie.",
       "Accomplissement personnel ; vous êtes à votre place.",
       "Un heureux aboutissement ; un grand cycle s'achève et un plus vaste s'ouvre."),
)

BY_NAME = {c.name: c for c in DECK}
